apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: application.malay.redhat.com
  #  Name must match the spec field in the form: <plural>.<group>
spec:
  group: malay.redhat.com
  #  Versions supported by this CustomResourceDefinition
  versions: 
    - name: v1
      #  Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                data1:
                  type: string
    #  Either Namespaced or Cluster
  scope: Namespaced 
  names:
    plural: application 
    singular: applications 
    kind: Application 
    shortNames:
    - app 