apiVersion: v1 
kind: Pod
metadata:
  name: example-for-secret
spec:
  containers:
    - name: secret-use
      image: k8s.gcr.io/nginx-slim:0.8
      env:
      - name: MY_PASSWORD
        valueFrom:
          secretKeyRef:
            name: test-secret
            key: password
      volumeMounts:
        - name: secret-volume #  Referring to the volume in the container to mount it
          mountPath: usr/share/nginx/
  volumes:
      - name: secret-volume
        secret:
          secretName: test-secret #  Specifying the configmap as the volume