apiVersion: apps/v1
kind: Deployment #  Specifying the Kubernetes object kind
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: test #  Matching the label
  replicas: 1 #  Telling how many copies of the pod we need
  template: #  Create pods using pod definition in this template
    metadata:
      labels:
        app: test #  Putting the label here
    spec:
      volumes:
        - name : mypvc
          persistentVolumeClaim:
            claimName: pvc01 # reference the pvc name
      containers:
      - name: test
        image: malayparida2000/multistage_example #  Specifying the image to be used for container
        ports:
        - containerPort: 8081 #  Exposing this port of the container
        volumeMounts:
        - mountPath: "/"
          name: mypvc
---
apiVersion: v1
kind: Service
metadata:
  name: test-service
spec:
  type: NodePort
  ports:
  - targetPort: 8081 #  Port of the target container
    port: 80 #  Port on which the service listens
    protocol: TCP
  selector:
    app: test #  Service will be linked to the deployment by this selector
