apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: demo 
 labels: # optional
  app: demo
spec: 
 replicas: 5 
 selector: 
  matchLabels:
   app: demo
 template:
  metadata: 
   labels: 
    app: demo
  spec:
   containers:
   - name: demo
     image: riya_demo_image31
     ports: 
     - containerPort: 8080